spring:
  application:
    name: vuce-cp-api-bs-pagos-command
  datasource:
    driver-class-name: ${DATABASE_DRIVER:org.postgresql.Driver}
    url: ${DATABASE_URL:jdbc:postgresql://192.168.140.23:5444/VUCE_CP}
    username: ${DATABASE_USER:cpcamagetricomapp}
    password: ${DATABASE_PASSWORD:pass_cpcamagetricomapp}
    hikari:
      maximum-pool-size: ${DATASOURCE_HIKARI_MAX_POOL_SIZE:20}
      minimum-idle: ${DATASOURCE_HIKARI_MIN_IDLE:5}
      connection-timeout: ${DATASOURCE_HIKARI_CNXTIMEOUT:10000}
      idle-timeout: ${DATASOURCE_HIKARI_IDLETIMEOUT:300000}
      max-lifetime: ${DATASOURCE_HIKARI_MAXLIFETIMEOUT:1800000}    
  jpa:
    show_sql: ${JPA_SHOW_SQL:true}
    generate-ddl: 'false'
    database-platform: ${DATABASE_DIALECT:org.hibernate.dialect.PostgreSQLDialect}
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    groups-order: DESC
    operationsSorter: method
    disable-swagger-default-url: true
    use-root-path: true
  api-docs:
    path: /api-docs
    version: openapi_3_1
feign:
  client:
    config:
      default:
        connectTimeout: ${FEIGN_CONNECT_TIMEOUT:5000}
        readTimeout: ${FEIGN_READ_TIMEOUT:5000}
        loggerLevel: ${FEIGN_LOGGER_LEVEL:full}
    pasarela-api:
      base-url: ${ORDENPAGO_SUNAT_API_URL:https://landing-desa.vuce.gob.pe/v1/vuce-services/pasarela}
    document-api:
      base-url: ${DOCUMENT_API_URL:http://router-default.apps.desarrollo.vuce.gob.pe/cp2/documento}
server:
  port: ${SERVER_PORT:8097}
  servlet:
    context-path: ${SERVER_CONTEXT_PATH:/cp2/pagos/command}